// Generated by gencpp from file base_joy_controller_pkg/adcm.msg
// DO NOT EDIT!


#ifndef BASE_JOY_CONTROLLER_PKG_MESSAGE_ADCM_H
#define BASE_JOY_CONTROLLER_PKG_MESSAGE_ADCM_H

#include <ros/service_traits.h>


#include <base_joy_controller_pkg/adcmRequest.h>
#include <base_joy_controller_pkg/adcmResponse.h>


namespace base_joy_controller_pkg
{

struct adcm
{

typedef adcmRequest Request;
typedef adcmResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct adcm
} // namespace base_joy_controller_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::base_joy_controller_pkg::adcm > {
  static const char* value()
  {
    return "a38fbaba7afb595971b872379e21f3c7";
  }

  static const char* value(const ::base_joy_controller_pkg::adcm&) { return value(); }
};

template<>
struct DataType< ::base_joy_controller_pkg::adcm > {
  static const char* value()
  {
    return "base_joy_controller_pkg/adcm";
  }

  static const char* value(const ::base_joy_controller_pkg::adcm&) { return value(); }
};


// service_traits::MD5Sum< ::base_joy_controller_pkg::adcmRequest> should match
// service_traits::MD5Sum< ::base_joy_controller_pkg::adcm >
template<>
struct MD5Sum< ::base_joy_controller_pkg::adcmRequest>
{
  static const char* value()
  {
    return MD5Sum< ::base_joy_controller_pkg::adcm >::value();
  }
  static const char* value(const ::base_joy_controller_pkg::adcmRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::base_joy_controller_pkg::adcmRequest> should match
// service_traits::DataType< ::base_joy_controller_pkg::adcm >
template<>
struct DataType< ::base_joy_controller_pkg::adcmRequest>
{
  static const char* value()
  {
    return DataType< ::base_joy_controller_pkg::adcm >::value();
  }
  static const char* value(const ::base_joy_controller_pkg::adcmRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::base_joy_controller_pkg::adcmResponse> should match
// service_traits::MD5Sum< ::base_joy_controller_pkg::adcm >
template<>
struct MD5Sum< ::base_joy_controller_pkg::adcmResponse>
{
  static const char* value()
  {
    return MD5Sum< ::base_joy_controller_pkg::adcm >::value();
  }
  static const char* value(const ::base_joy_controller_pkg::adcmResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::base_joy_controller_pkg::adcmResponse> should match
// service_traits::DataType< ::base_joy_controller_pkg::adcm >
template<>
struct DataType< ::base_joy_controller_pkg::adcmResponse>
{
  static const char* value()
  {
    return DataType< ::base_joy_controller_pkg::adcm >::value();
  }
  static const char* value(const ::base_joy_controller_pkg::adcmResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BASE_JOY_CONTROLLER_PKG_MESSAGE_ADCM_H
